configService:
  replicaCount: 3
  fullNameOverride: "apollo-configservice"
  image:
    repository: uhub.service.ucloud.cn/entropypool/apollo-configservice
    tag: 1.9.1.1
    pullPolicy: IfNotPresent

adminService:
  replicaCount: 1
  fullNameOverride: "apollo-adminservice"
  image:
    repository: uhub.service.ucloud.cn/entropypool/apollo-adminservice
    tag: 1.9.1.1
    pullPolicy: IfNotPresent

configdb:
  connectionStringProperties: characterEncoding=utf8&useSSL=false
