configService:
  replicaCount: 3
  fullNameOverride: "apollo-configservice"
  image:
    repository: entropypool/apollo-configservice
    tag: 1.9.1
    pullPolicy: IfNotPresent

adminService:
  replicaCount: 3
  fullNameOverride: "apollo-adminservice"
  image:
    repository: entropypool/apollo-adminservice
    tag: 1.9.1
    pullPolicy: IfNotPresent

configdb:
  connectionStringProperties: characterEncoding=utf8&useSSL=false
  userName: "root"
  password: "root"
  host: "mysql"
